### ISSUE TITLE
Define the certificate-authority flag

### ISSUE THREAD

**Issue by jliburd-nsi** [redhat-developer/openshift-vsts#120]
Is there a way to define the --certificate-authority flag when defining the OpenShift service connection so that it is used when the "oc login" command is used?

I am getting an error right now with the "Install and Setup" task. The error is: 

"error: The server uses a certificate signed by unknown authority. You may need to use the --certificate-authority flag to provide the path to a certificate file for the certificate authority, or --insecure-skip-tls-verify to bypass the certificate check and use insecure connections."

**Comment by lstocchi** [comment]
Hi @jliburd-nsi, no there is no way to add --certificate-authority atm. You can try using the --insecure-skip-tls-verify flag. Just select the "Accept untrusted SSL certificate" option in the openshift service connection. Let me know if it works.

![image](https://user-images.githubusercontent.com/49404737/68957650-c352e780-07ca-11ea-939e-1cc4e43175e6.png)

**Comment by jliburd-nsi** [comment]
Hi, 

Thanks for the fast response.

Yes it works when I check the "Accept untrusted SSL certificates" box but I didn't want to check that option. 

I tested the login from the server itself with the --certificate-authority flag and it worked so I was just trying to find a way to set that option through the plugin.

**Comment by lstocchi** [comment]
I'll work on this new feature and i'll let you know when it's available. Thanks for your feedback :)

**Comment by lstocchi** [comment]
New version released. Now you can set up the certificate flag when creating/editing openshift service connection. Feel free to open another github issue if you face any problem. Thank you :)
