### ISSUE TITLE
OC install and setup fails

### ISSUE THREAD

**Issue by cvanhalt** [redhat-developer/openshift-vsts#135]
Task Install and setup oc fails on on prem linux build agent with the following error:
`##[error]request to https://mirror.openshift.com/pub/openshift-v3/clients/3.11.154/linux/oc.tar.gz failed, reason: connect ETIMEDOUT 54.173.18.88:443`

I'm running behind a corporate proxy, but exported HTTP_PROXY and HTTPS_PROXY.
I also provided proxy details during agent setup.

When I run 
`/usr/bin/curl -s -L -o https://mirror.openshift.com/pub/openshift-v3/clients/3.11.154/linux/oc.tar.gz `
directly on the agent it works.

Thanks,
Chris

**Comment by lstocchi** [comment]
Hi @cvanhalt , i have to admit that i never tried it with a proxy and i promise i'll make some test. One idea is to add a -x flag to the curl toolrunner inside the `downloadAndExtract` method in `oc-install.js`.
Just go to your agent action location (i.e `/home/luca/azure/myagent/_work/_tasks/oc-cmd_ebaf1cdc-a60f-4e57-ba29-e3b8f80aeb1e/2.0.12/lib`) -> open oc-install.js -> edit the curl ToolRunner to have something like:
```
let curl: ToolRunner = tl.tool('curl');
      curl
        .arg('-s')
        .arg('-L')
        .arg('-o')
        .arg(archivePath)
        .arg('-x')
        .arg('53.21.321.32:7000') <-- use your proxy
        .arg(url);
      await curl.exec();
```
save it and run your agent locally again.
I'm not sure this will work but i'll try to test it and find a working solution.
Let me know if you test it somehow.
Thank you.

**Comment by cvanhalt** [comment]
Hi @lstocchi, thanks for looking into this.
I added the suggested lines to oc-install.js and re-ran the pipeline, unfortunately without success.
Anyway, I think curl will use the env variables http_proxy and https_proxy by default.

Many thanks,
Chris

**Comment by lstocchi** [comment]
@cvanhalt i tried by using a proxy i had. Not so fast but at least i had the confirmation curl was using it lol... When you run it, in the azure panel, can you see the correct proxy printed in the console? Like the one in red i had below? 
![proxy](https://user-images.githubusercontent.com/49404737/73674719-6a9c3800-46b1-11ea-9974-fa49440f9a70.png)

**Comment by cvanhalt** [comment]
Hi @lstocchi , unfortunately I only see the following error mesage..
![image](https://user-images.githubusercontent.com/21121839/73735298-569f1780-473f-11ea-98ff-33215651c254.png)

**Comment by cvanhalt** [comment]
@lstocchi seems like the Cipheriv warning could be fixed if you update the task-lib to a newer version.
See: https://github.com/microsoft/azure-pipelines-tasks/issues/12147#issuecomment-577711497

**Comment by cvanhalt** [comment]
This is what I get when I use curl directly on the agent
![image](https://user-images.githubusercontent.com/21121839/73742924-c0beb900-474d-11ea-9b02-fe6d75049c2e.png)

**Comment by lstocchi** [comment]
> @lstocchi seems like the Cipheriv warning could be fixed if you update the task-lib to a newer version.
> See: [microsoft/azure-pipelines-tasks#12147 (comment)](https://github.com/microsoft/azure-pipelines-tasks/issues/12147#issuecomment-577711497)

Yes, they will be updated in next release https://github.com/redhat-developer/openshift-vsts/pull/137

**Comment by lstocchi** [comment]
> This is what I get when I use curl directly on the agent
> ![image](https://user-images.githubusercontent.com/21121839/73742924-c0beb900-474d-11ea-9b02-fe6d75049c2e.png)

Ok, thank you!! i'm trying to replicate it on my machine. Let you know if i have some success with it. 

I don't know if you know it or which is your pipeline but if you need to execute oc cmds you can still tell the extension to use your local oc cli without making it download a new one everytime. This is no ideal but this could be an option until we find out a fix.

**Comment by cvanhalt** [comment]
@lstocchi, with the oc cmd task 
![image](https://user-images.githubusercontent.com/21121839/73746697-113a1480-4756-11ea-93b7-29ffa30e21d4.png)

it still tries to download the client.
Also the -x proxy is missing, although it is in the oc-install.js

![image](https://user-images.githubusercontent.com/21121839/73746671-05e6e900-4756-11ea-8305-5591b5dfc8b7.png)

**Comment by lstocchi** [comment]
@cvanhalt if you run `which oc` on your terminal which is the output? The extension uses the oc cli found in that way and, if not present, it will try to download it from openshift website. It seems like the extension doesn't find it. Your inputs are correct.

The -x proxy is missing bc you edited the oc-install.js inside oc-setup folder. You should edit the oc-install.js in your oc-cmd folder.

**Comment by cvanhalt** [comment]
@lstocchi , thanks a lot for your help!
The rest seems like a firewall topic on my side, as I get the same error when executing directly on the host...
![image](https://user-images.githubusercontent.com/21121839/73749701-2ade5a80-475c-11ea-9bf6-4fa2b95248fd.png)

**Comment by lstocchi** [comment]
@cvanhalt yeahh!! i'm glad we did some progress :) i should definitely add that -x flag to the extension. It could be useful to others. Let me know if you encounter other issues. 

I'll keep investigating on the timedout error you had in the oc-setup to see if i can replicate and fix that. :+1:

**Comment by cvanhalt** [comment]
@lstocchi , really cool, as now from my side no blocker is left and I can deploy to openshift :)
Thanks a lot again!
