### ISSUE TITLE
Use the task with a kubeconfig path or inline config

### ISSUE THREAD

**Issue by rinormaloku** [redhat-developer/openshift-vsts#146]
In addition to authenticating by using the OpenShift Service connection, expand the possibilities to:
- Specify a KUBECONFIG path where the kubeconfig file can be found
- Specify INLINE kubernetes configuration.

Both of these features are supported from the **kubectl** task, and it would be great to have them here as well.

**Comment by lstocchi** [comment]
Closing it. #147 merged
