### ISSUE TITLE
oc-setup should cache the tool 

### ISSUE THREAD

**Issue by superslowloris** [redhat-developer/openshift-vsts#151]
Most tool installer tasks cache the tool for future usage.

A good example of this is the Docker CLI installer ([source code](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/DockerInstallerV0))
The caching is provided by the official [Azure Pipelines Tool Installer SDK](https://github.com/microsoft/azure-pipelines-tool-lib)

**Comment by lstocchi** [comment]
Hi @superslowloris, thanks for opening this issue and sorry for the late response. I have to check about it because it doesn't make much sense for me using the caching for the oc-setup action. 

If someone is using a self-hosted agent the oc-setup will download the oc cli requested if not present, so in the next calls/execution if the same oc cli version is used, this will not be downloaded again. 
If someone is using a Microsoft-hosted agent i don't know if the cache will work on different pipeline executions, needs to verify that.

**Comment by superslowloris** [comment]
Hi @lstocchi 

Thank you for replying. On my org we are using self-hosted agents. And our builds would sometimes have a huge spike in duration and we tracked it down to the oc-setup task, that would sometimes take up to 17 minutes even when running on agents that already had downloaded the tool previously.

It got so frequent that we had to replace the task with a custom Powershell script to install the tool when not present.

Another benefit we saw from the script was the isolation of the KUBECONFIG directory. We found out that some agents actually run on the same physical machine and were interfeering with each other. I believe this is something the oc-setup tool does not do by itself.

**Comment by lstocchi** [comment]
Hi @superslowloris, that's bad. Do you use a proxy? Which oc cli version are you using?
Could you provide your custom Powershell script? Just the part where it downloads oc cli? Do you also have oc-cmd tasks in your pipeline? Did they give you any issue? I'll give a look a the code to see if i missed something

**Comment by lstocchi** [comment]
Found out why it downloads a new cli when it shouldn't. I'll fix that asap. Still not sure why it takes 17 minutes to set up oc. It's seriously too much.

**Comment by superslowloris** [comment]
@lstocchi 

> Could you provide your custom Powershell script?

On our builds/releases we have a poweshell task that imports a custom powershell module with openshift related commands. In this module we have a command to install a specific version of the CLI in an agent :
```Powershell
function Install-OpenshiftCliForLinux {
    [CmdletBinding()]
    param (
        [string]$version,
        [string]$toolDirectory,
        [string]$tempDirectory,
        [string]$kubeconfigDirectory)
    
        # Ensure the tool directory exists
        mkdir -p $toolDirectory 
        
        # Check if the tool already exists before downloading
        $toolPath = "$toolDirectory/oc"
        if(-Not (Test-Path $toolPath)){

          Write-Host "Downloading from https://mirror.openshift.com/pub/openshift-v3/clients/$version/linux/oc.tar.gz"
          Invoke-WebRequest https://mirror.openshift.com/pub/openshift-v3/clients/$version/linux/oc.tar.gz -OutFile "$tempDirectory/oc.tar.gz"
          Write-Host ""
          Write-Host "Extracting archive to $toolDirectory"
          tar -xzf "$tempDirectory/oc.tar.gz" -C "$toolDirectory/"
        }
        else {
          Write-Host "Tool already exists"
        }

        Write-Host ""
        Write-Host "Add $toolDirectory to PATH"
        $env:PATH="$toolDirectory" +":" + $env:PATH
        
        Write-Host ""
        Write-Host "Set environment variable: KUBECONFIG=$kubeconfigDirectory/kubeconfig"
        $env:KUBECONFIG = "$kubeconfigDirectory/kubeconfig"
}
```

Then our powershell tasks call it with agent specific paths:
```Powershell
$ocCliVersion = "3.11.188"

Install-OpenshiftCliForLinux `
   -version  $ocCliVersion `
   -toolDirectory "$(Agent.ToolsDirectory)/oc/$ocCliVersion" `
   -tempDirectory $(Agent.TempDirectory) `
   -kubeconfigDirectory $(Agent.TempDirectory)
```

> Do you also have oc-cmd tasks in your pipeline?

Since we already have a powershell script to install the CLI and with the global KUBECONFIG issue I mentioned in the previous post we instead just issue the oc specific commands from withing the same script.

**Comment by superslowloris** [comment]
> Found out why it downloads a new cli when it shouldn't. I'll fix that asap. Still not sure why it takes 17 minutes to set up oc. It's seriously too much.

We certainly don't blame the task for the time to download. That is most likely networking issues downloading the tool. 

Have a version of the task that does not download it when it is already present will certainly get rid of most of the cases we experienced.

**Comment by lstocchi** [comment]
> We certainly don't blame the task for the time to download. That is most likely networking issues downloading the tool.
> 
> Have a version of the task that does not download it when it is already present will certainly get rid of most of the cases we experienced.

Perfect. I'll ping you once the extension will be updated and released. Sorry for the trouble.
