### ISSUE TITLE
Error on oc download: unknown archive format

### ISSUE THREAD

**Issue by davidda** [redhat-developer/openshift-vsts#201]
Hi, I get this error when specifying a custom download URL for the oc tool:
![image](https://user-images.githubusercontent.com/4145824/208608734-846c2145-c8da-4fd2-86b6-bad8d4c8acfc.png)

If I log in to the agent the downloaded file can be manually extracted just fine.

I'm on Azure DevOps Server 2020 with an Ubuntu 20 agent version 2.204.

**Comment by lstocchi** [comment]
Hi @davidda , could you send me the custom download url? So i can replicate your exact steps. Thanks

**Comment by davidda** [comment]
@lstocchi Yes, I'd be happy to send it but I'm not sure we can share it publicly. Is there a way to send it to you in private?

**Comment by lstocchi** [comment]
You can send me an email. lstocchi [at] redhat.com

**Comment by lstocchi** [comment]
Thanks @davidda , received :+1: . I'll give it a look in the afternoon and let you know asap

**Comment by lstocchi** [comment]
@davidda found the issue. Apparently there was no working code for `.tar` archives.
A workaround could be to change the archive extension to `.tar.gz` and see if it works. 
I've created a PR to fix this and I hope to make a release in the next hours. Sorry for the trouble :pray:

**Comment by davidda** [comment]
Thank you so much for the swift support. I will wait for the release because we don't have control over the archive extension.

**Comment by lstocchi** [comment]
@davidda new version 2.0.0 released. It also contains an update on all tasks as we needed to upgrade everything to node10. So pay attention to the task version used (it's 3. now0.1) when changing your pipeline. 
For anything broken, please open an issue. Thank you for your help!! :pray:
