### ISSUE TITLE
Use nock to mock tests running against GitHub

### ISSUE THREAD

**Issue by hferentschik** [redhat-developer/openshift-vsts#75]
Some tests run against GitHub and download oc realese binaries, etc. This can cause issues with the build failing due to exceeding the GitHub API rate limit. For pull requests it even does not help to set a GITHUB_TOKEN, since hidden variables are not injected in pull requests initiated from another repository. 

Using nock the GitHub based tests can be changed to not access GitHub:

- No issue with rate limit 
- Tests run locally w/o network
- Tests run faster

**Comment by hferentschik** [comment]
https://www.npmjs.com/package/nock

**Comment by hferentschik** [comment]
On second thought, it might not be so easy, since we are not downloading via the Node API, but rather calling out to _curl_. So one either needs to mock this call or switch to an approach where we download the binary without calling out to a system binary.

**Comment by lstocchi** [comment]
Tests were rewritten by using sinon https://github.com/redhat-developer/openshift-vsts/pull/98 . Closing it.
