### ISSUE TITLE
Enhancement: use on agent not connected to the WEB

### ISSUE THREAD

**Issue by gt97** [redhat-developer/openshift-vsts#97]
This is an enhancement request.
In my configuration I have the agent and openshift installed in a protected environment witho no internet accessl.
It would be fantastic if the exection of the plugin, before searching for the version on the web verifies if the oc installed on the build agent if already the version corresponding the version reqested. In this scenario no internet connection is required.
As a small checklist I suggest:
if oc exists -> oc version -> if the oc-version is the same version requested in the configuration of the plugin (Version of oc to use) then use the oc installed

TIA
Kindly
Gianluca

**Comment by lstocchi** [comment]
Hi @gt97 , sorry, i've been busy in last two weeks and i wasn't able to work on this enhancement. Thank you for your suggestion, we will work on it in this sprint ;)

**Comment by lstocchi** [comment]
PR https://github.com/redhat-developer/openshift-vsts/pull/102 merged. A new version of Openshift VSTS will be released the next week. Closing it
